### ISSUE TITLE
Not all changes trigger config save on exit

### ISSUE THREAD

**Issue by OoMrFlibble** [OoMrFlibble/oolite-debug-console-flibble#4]
def optionsChanged

Some changes are NOT detected. e.g. orig and curr are the same even if background changed.

examples of not detected as changes
debug toggle
colours

examples of detected
save commmand history on exit
showconsole

If a detected change causes save, all changes get saved, including those which would not have been detected.

The earliest I'm catching this is shown below. Change background colour only, and it's not picked up here.
```
    def optionsChanged(self):    # check if any options have changed before writing
        orig, curr = self.loadedConfig, self.localOptions
        #FLIBBLEDEBUG BLOCK START
        if orig == curr:
            print("FLIBBLEDEBUG IT'S ALL THE SAME")
        else:
            print("FLIBBLEDEBUG SOMETHING DIFFERS")
        #FLIBBLEDEBUG BLOCK END
```

**Comment by Oocag** [comment]
on it

**Comment by OoMrFlibble** [comment]
That got it!
